##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

## Call this flow using: liquibase flow --flow-file=flowfiles/liquibase-premerge.flowfile.yaml

stages:

  PreMerge-Checks:
    actions:
      - type: liquibase
        command: checks run
        cmdArgs: { checks-scope: changelog, 
          checks-settings-file: "policychecks/liquibase.checks-settings.conf", 
          auto-update: "ON", 
          changeset-filter: "pending" 
        }
        globalArgs: { 
          reports-name: "checks-report-premerge.html" 
        }