##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

## Call this flow using: liquibase flow --flow-file=flowfiles/liquibase-rollback.flowfile.yaml

stages:

  Rollback-SQL:
    actions:
      - type: liquibase
        command: rollback-one-update-sql
        
  Rollback:  
    actions:
      - type: liquibase
        command: rollback-one-update
        cmdArgs: { 
          force: true
        }

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history